export const CATEGORIES = 'CATEGORIES';
export const CATEGORIES_FULFILLED = 'CATEGORIES_FULFILLED';
export const CATEGORIES_REJECTED = 'CATEGORIES_REJECTED';

export const EMPLOYEES = 'EMPLOYEES';
export const EMPLOYEES_FULFILLED = 'EMPLOYEES_FULFILLED';
export const EMPLOYEES_REJECTED = 'EMPLOYEES_REJECTED';
